config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :portfolios, except: [:show]
  # this will change the route for localhost:3000/angular
  get 'angular', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  # we can do get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
  # For detaßils on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies

  #it's important to follow this type of pattern
  accepts_nested_attributes_for :technologies, 
                                reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image, message: "can't be blank"

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  #another way to filter on subtitle
  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  #after_initialize happens after the "new" method in the controller.  after_create happens after the "create" method in the controller class
  after_initialize :set_defaults

  # the pipe means only set the value if the variable at the left side of the equal sign is nil.
  def set_defaults

    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_port, only:[:show, :edit, :update, :destroy]
  layout "portfolio"

  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update]}, admin: :all

  def index
    @portfolio_items = Portfolio.by_position
    # @portfolio_items = Portfolio.where(subtitle: "Ruby on Rails")
    # 
    # shouldn't have too much logic in the controller
    #@portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save 
        # the redirect changes the path to the list instead of show.
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' } # @portfolio_item will redirect to port's show page.
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

    @set_port
    
  end
  
  def update

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item}
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully removed.' }
    end
  end

  private
   def set_port
    @portfolio_item = Portfolio.find(params[:id])
   end

    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        technologies_attributes: [:name]
                                      )
    end

  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control'%>
      </div>

      <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control'%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control'%>
      </div>
    </div>
  </div>

  <hr>
  
  <div class="col-md-12">
    <div>
      <%=f.fields_for :technologies do |technology_form| %>
      <div>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: 'form-control'%>
      </div>
      <%end%>
    </div>

    <div class="actions">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block'%>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 card">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%> 
  <p class="card-text">
    <span>
      <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
    </span>
    <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<a href="portfolios/new">Create New Item</a>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:admin)%>

<% @angular_portfolio_items.each do |port| %>
  <p><%= link_to port.title, portfolio_show_path(port) %></p>
  <p><%= port.subtitle %></p>
  <p><%= port.body %></p>
  <p><%= image_tag port.thumb_image unless port.thumb_image.nil?%></p>
  <%= link_to "Edit Angular Portfolio Item", edit_portfolio_path(port) if logged_in?(:admin) %>
  <%= link_to 'Delete angular portfolio item', portfolio_path(port), method: :delete, data: {confirm: 'Are you sure?'}  if logged_in?(:admin)%>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<!-- div class="album py-5 bg-light text-muted" -->
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row sortable">
      <!-- %= link_to "Create New Item", new_portfolio_path if logged_in?(:admin) % -->
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <h2>Technologies used:</h2>
      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>